name: Simple Autotests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']


jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests and generate report
      run: pytest --junitxml=report.xml

    - name: Publish Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Pytest Report
        path: report.xml
        reporter: java-junit
        fail-on-error: false
